"""Sac-backed runner: spin up a sac agent, POST prompts via A2A, tear down.

This is newb 0.6's only runtime backend. It delegates ALL of:
  - runtime selection (local / docker / apptainer / remote)
  - auth (subscription token, API key, OAuth refresh)
  - isolation (namespace / sandbox / container)
  - Claude Code session lifecycle (multiplexer, hooks, MCP wiring)
… to scitex-agent-container (sac). newb only knows the A2A protocol.

The current sac handler is ``claude_cli`` (calls ``claude --print``
under the hood). When sac grows ``claude_session`` (talks to the
interactive multiplexer pane), newb gets the upgrade transparently —
no code change here, only the YAML template's ``handler`` field.
"""

from __future__ import annotations

import json
import shutil
import socket
import subprocess
import tempfile
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path


_AGENT_YAML_TEMPLATE = """\
# Auto-generated by newb. Do not edit.
apiVersion: scitex-agent-container/v3

kind: Agent

metadata:
  labels:
    role: newb-target
    team: newb
    project: newb
    function: "Smoke-test target spawned by newb. Reads .md skills under the mounted dir, answers brief questions, then idles. Auto-stopped by newb after the run."
    capabilities: smoke-target,read-only,brief-responder

spec:
  runtime: claude-code
  model: "{model}"
  multiplexer: tmux
  workdir: {workdir}

  host:
    - {host}

  a2a:
    port: {a2a_port}
    handler: claude_cli
    host: 127.0.0.1

  # Bump claude_cli handler's per-request timeout (default 25s). Our
  # smoke prompts ask the agent to read several .md files; that's
  # routinely 30-90s on Haiku.
  env:
    SAC_A2A_CLAUDE_TIMEOUT_S: "120"

  claude:
    flags:
      - --dangerously-skip-permissions
    session: continue-or-new

  python-venv:
    - ~/.venv
    - ~/.venv-3.11

  health:
    enabled: false

  restart:
    policy: never

  startup_commands:
    - delay: 3
      command: "You are newb-{tag}, a smoke-test target. Reply briefly to incoming A2A prompts; do NOT chat or ask follow-ups. Idle until questions arrive."
"""


def _free_port() -> int:
    """Find a free localhost port (race-y but adequate for one-shot use)."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


def _wait_for_a2a(port: int, agent_name: str, timeout: float = 60.0) -> None:
    """Block until the sidecar's per-agent endpoint is reachable."""
    url = f"http://127.0.0.1:{port}/v1/agents/{agent_name}/.well-known/agent.json"
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2.0) as r:
                if r.status == 200:
                    return
        except (urllib.error.URLError, ConnectionError, OSError):
            pass
        time.sleep(1.0)
    raise RuntimeError(
        f"sac A2A sidecar at :{port} never became ready (waited {timeout}s)"
    )


class SacRunner:
    """Lifecycle wrapper around a one-off sac agent for a single newb run.

    Generates a YAML, starts the agent, exposes ``run(prompt)`` for N
    A2A POSTs against the same long-lived container, then ``close()``
    tears it down.
    """

    def __init__(
        self,
        *,
        skills_mount: Path,
        model: str = "claude-haiku-4-5",
        host: str = "ywata-note-win",
    ):
        # Sanity check: sac must be installed.
        if not shutil.which("scitex-agent-container"):
            raise RuntimeError(
                "SacRunner requires `scitex-agent-container` on PATH "
                "(`pip install scitex-agent-container`)."
            )
        self.skills_mount = Path(skills_mount).resolve()
        self.tag = uuid.uuid4().hex[:8]
        self.name = f"newb-{self.tag}"
        self.port = _free_port()
        self.model = model
        # Workspace dir sac creates per agent. We let sac own it; we just
        # make a tmp YAML somewhere it can read.
        self.workdir = (
            Path.home() / ".scitex" / "orochi" / "runtime" / "workspaces" / self.name
        )
        self.skills_path = str(self.workdir / ".claude" / "skills")
        self._yaml_dir = Path(tempfile.mkdtemp(prefix=f"newb-yaml-{self.tag}-"))
        self._yaml_path = self._yaml_dir / f"{self.name}.yaml"
        self._yaml_path.write_text(
            _AGENT_YAML_TEMPLATE.format(
                model=model,
                workdir=self.workdir,
                host=host,
                a2a_port=self.port,
                tag=self.tag,
            )
        )
        self._started = False

    def start(self) -> None:
        # sac's a2a sidecar inherits env from this process (its `Popen`
        # call doesn't pass `env=`, and `spec.env` in the agent YAML
        # only reaches the Claude Code session, not the sidecar). So we
        # set SAC_A2A_CLAUDE_TIMEOUT_S here — the smoke prompts read
        # several .md files and routinely take 30-90s on Haiku, blowing
        # past sac's 25s default.
        import os as _os

        env = dict(_os.environ)
        env.setdefault("SAC_A2A_CLAUDE_TIMEOUT_S", "120")
        proc = subprocess.run(
            ["scitex-agent-container", "start", str(self._yaml_path)],
            capture_output=True,
            text=True,
            timeout=120,
            env=env,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"sac start failed (rc={proc.returncode}): "
                f"{proc.stderr[:500] or proc.stdout[:500]}"
            )
        self._started = True
        # Stage the skills under the agent's workspace .claude/skills/<pkg>/
        # so the prompts can reference {skills_path}.
        target = Path(self.skills_path) / self.skills_mount.name
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            shutil.rmtree(target, ignore_errors=True)
        shutil.copytree(self.skills_mount, target)
        _wait_for_a2a(self.port, self.name)

    def run(self, prompt: str, *, model: str | None = None, timeout: int = 120) -> dict:
        """POST a prompt via A2A SendMessage; return ``{"result": text}``.

        Shape is compatible with newb's existing ``_extract_text`` helper.
        ``model`` is ignored (sac fixes it at agent-start time).
        """
        if not self._started:
            self.start()
        msg_id = uuid.uuid4().hex[:12]
        body = json.dumps(
            {
                "jsonrpc": "2.0",
                "id": msg_id,
                "method": "SendMessage",
                "params": {
                    "message": {
                        "role": "ROLE_USER",
                        "parts": [{"text": prompt}],
                        "messageId": msg_id,
                    }
                },
            }
        ).encode("utf-8")
        url = f"http://127.0.0.1:{self.port}/v1/agents/{self.name}"
        req = urllib.request.Request(
            url,
            data=body,
            headers={
                "Content-Type": "application/json",
                "A2A-Version": "1.0",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                payload = json.loads(resp.read().decode("utf-8"))
        except urllib.error.URLError as e:
            raise RuntimeError(f"A2A POST failed: {e}") from e
        if "error" in payload:
            raise RuntimeError(f"A2A error: {payload['error']}")
        # Extract assistant text.
        try:
            parts = payload["result"]["task"]["status"]["message"]["parts"]
            text = next((p["text"] for p in parts if "text" in p), "")
        except (KeyError, TypeError, StopIteration):
            text = json.dumps(payload)[:500]
        return {"result": text}

    def close(self) -> None:
        if self._started:
            try:
                subprocess.run(
                    ["scitex-agent-container", "stop", self.name],
                    capture_output=True,
                    timeout=60,
                )
            except Exception:
                pass
            self._started = False
        if self._yaml_dir.exists():
            shutil.rmtree(self._yaml_dir, ignore_errors=True)
